create extension if not exists pgcrypto;

create type public.utility_type as enum ('water', 'electricity');
create type public.reading_source as enum ('manual', 'receipt_import');

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references public.profiles (id) on delete cascade,
  address_label text not null,
  timezone text not null default 'Africa/Windhoek',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.meters (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties (id) on delete cascade,
  utility_type public.utility_type not null,
  meter_number text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  unique (property_id, meter_number)
);

create table if not exists public.meter_readings (
  id bigint generated by default as identity primary key,
  meter_id bigint not null references public.meters (id) on delete cascade,
  reading_value numeric(12, 3) not null check (reading_value >= 0),
  reading_timestamp timestamptz not null,
  source public.reading_source not null default 'manual',
  created_by uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.purchase_receipts (
  id bigint generated by default as identity primary key,
  meter_id bigint not null references public.meters (id) on delete cascade,
  meter_number text not null,
  token text not null,
  receipt_number text not null,
  purchase_timestamp timestamptz not null,
  amount numeric(12, 2) not null check (amount >= 0),
  units numeric(12, 3) not null check (units >= 0),
  utility_provider text not null,
  cents_per_unit numeric(12, 4) not null check (cents_per_unit >= 0),
  vat_amount numeric(12, 2) check (vat_amount is null or vat_amount >= 0),
  vat_number text,
  customer_name text,
  address text,
  raw_payload text,
  idempotency_key text not null,
  created_by uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  unique (idempotency_key)
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  actor_user_id uuid references public.profiles (id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.usage_snapshots (
  id bigint generated by default as identity primary key,
  meter_id bigint not null references public.meters (id) on delete cascade,
  period_start date not null,
  period_end date not null,
  units_used numeric(12, 3) not null default 0 check (units_used >= 0),
  estimated_cost numeric(12, 2) not null default 0 check (estimated_cost >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  unique (meter_id, period_start, period_end)
);

create index if not exists idx_properties_owner_user_id
  on public.properties (owner_user_id);

create index if not exists idx_meters_property_id
  on public.meters (property_id);

create index if not exists idx_meter_readings_meter_timestamp
  on public.meter_readings (meter_id, reading_timestamp desc);

create index if not exists idx_purchase_receipts_meter_timestamp
  on public.purchase_receipts (meter_id, purchase_timestamp desc);

create index if not exists idx_purchase_receipts_created_by
  on public.purchase_receipts (created_by);

create index if not exists idx_audit_events_entity
  on public.audit_events (entity_type, entity_id, created_at desc);

create index if not exists idx_usage_snapshots_meter_period
  on public.usage_snapshots (meter_id, period_start desc, period_end desc);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', '')
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.current_user_owns_property(target_property_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.properties p
    where p.id = target_property_id
      and p.owner_user_id = auth.uid()
  );
$$;

create or replace function public.current_user_owns_meter(target_meter_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.meters m
    join public.properties p on p.id = m.property_id
    where m.id = target_meter_id
      and p.owner_user_id = auth.uid()
  );
$$;

create or replace function public.log_purchase_receipt_audit_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.audit_events (
    entity_type,
    entity_id,
    action,
    actor_user_id,
    payload
  )
  values (
    'purchase_receipt',
    coalesce(new.id, old.id)::text,
    tg_op,
    coalesce(new.created_by, old.created_by),
    jsonb_build_object(
      'meter_id', coalesce(new.meter_id, old.meter_id),
      'receipt_number', coalesce(new.receipt_number, old.receipt_number),
      'purchase_timestamp', coalesce(new.purchase_timestamp, old.purchase_timestamp)
    )
  );

  return coalesce(new, old);
end;
$$;

drop trigger if exists purchase_receipts_audit_trigger on public.purchase_receipts;

create trigger purchase_receipts_audit_trigger
after insert or update on public.purchase_receipts
for each row execute procedure public.log_purchase_receipt_audit_event();

alter table public.profiles enable row level security;
alter table public.properties enable row level security;
alter table public.meters enable row level security;
alter table public.meter_readings enable row level security;
alter table public.purchase_receipts enable row level security;
alter table public.usage_snapshots enable row level security;
alter table public.audit_events enable row level security;

create policy "Profiles are self readable"
on public.profiles
for select
to authenticated
using (id = auth.uid());

create policy "Profiles are self writable"
on public.profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy "Properties are owned by current user"
on public.properties
for select
to authenticated
using (owner_user_id = auth.uid());

create policy "Users can insert their own properties"
on public.properties
for insert
to authenticated
with check (owner_user_id = auth.uid());

create policy "Users can update their own properties"
on public.properties
for update
to authenticated
using (owner_user_id = auth.uid())
with check (owner_user_id = auth.uid());

create policy "Users can read owned meters"
on public.meters
for select
to authenticated
using (public.current_user_owns_property(property_id));

create policy "Users can insert meters on owned properties"
on public.meters
for insert
to authenticated
with check (public.current_user_owns_property(property_id));

create policy "Users can update owned meters"
on public.meters
for update
to authenticated
using (public.current_user_owns_property(property_id))
with check (public.current_user_owns_property(property_id));

create policy "Users can read readings for owned meters"
on public.meter_readings
for select
to authenticated
using (public.current_user_owns_meter(meter_id));

create policy "Users can insert readings for owned meters"
on public.meter_readings
for insert
to authenticated
with check (
  public.current_user_owns_meter(meter_id)
  and created_by = auth.uid()
);

create policy "Users can read receipts for owned meters"
on public.purchase_receipts
for select
to authenticated
using (public.current_user_owns_meter(meter_id));

create policy "Users can insert receipts for owned meters"
on public.purchase_receipts
for insert
to authenticated
with check (
  public.current_user_owns_meter(meter_id)
  and created_by = auth.uid()
);

create policy "Users can read usage snapshots for owned meters"
on public.usage_snapshots
for select
to authenticated
using (public.current_user_owns_meter(meter_id));

create policy "Users can read their own audit events"
on public.audit_events
for select
to authenticated
using (actor_user_id = auth.uid());
