create table if not exists public.meter_balance_snapshots (
  id bigint generated by default as identity primary key,
  meter_id bigint not null references public.meters (id) on delete cascade,
  available_units numeric(12, 3) not null check (available_units >= 0),
  recorded_at timestamptz not null,
  source text not null default 'manual_entry',
  created_by uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_meter_balance_snapshots_meter_timestamp
  on public.meter_balance_snapshots (meter_id, recorded_at desc);

alter table public.meter_balance_snapshots enable row level security;

create policy "Users can read balances for owned meters"
on public.meter_balance_snapshots
for select
to authenticated
using (public.current_user_owns_meter(meter_id));

create policy "Users can insert balances for owned meters"
on public.meter_balance_snapshots
for insert
to authenticated
with check (
  public.current_user_owns_meter(meter_id)
  and created_by = auth.uid()
);
